project:
  type: website
  output-dir: docs
  
website:
  title: "BLGY5121M Adv Stats"
  navbar:
    left:
      - href: index.qmd
        text: Advanced Statistics
      - aiandgraphs.qmd
      - lm.qmd
      - power.qmd
      - multivariatemethods.qmd
      - mixedmodels1.qmd
      - mixedmodels2.qmd
      - spatial.qmd
      - metaanalyses.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/acriach/BLGY5121MAdvStats
  page-footer:
    right: "[Source](https://github.com/acriach/BLGY5121MAdvStats)"
    left: "[CC Licensed](https://creativecommons.org/)"

format:
  html:
    theme: cerulean
    toc: true

editor: source

