---
title: "Finally"

execute: 
  warning: false
  message: false
---

# Finally

## How to share code

Ideas around sharing code are not new as this [2015 post](https://ramblingsofanecologa.wordpress.com/2015/10/23/publish-and-share-your-code/) shows.

<br>

For examples of how to format your code see below. Reassure yourself that their code is not necessarily easy to understand at first glance but that they try to explain their code through succinct annotations. 


### Example 1

Culina, A., van den Berg, I., Evans, S. and Sánchez-Tójar, A. 2020. [Low availability of code in ecology: A call for urgent action.](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000763) PLoS Biology. 18(7), p.e3000763. 
 
See the correction for the data availability statement. Find the link that takes you to Zenodo, download the zip file and extract it. Open one of the .R script files in Rstudio and look at what information they have included and how they have formatted their code before sharing. 

<br>

### Example 2

Jones, P.F., Jakes, A.F., Eacker, D.R. and Hebblewhite, M. 2020. [Annual pronghorn survival of a partially migratory population.](https://wildlife.onlinelibrary.wiley.com/doi/10.1002/jwmg.21886) The Journal of Wildlife Management. 84(6), pp.1114-1126. 

Just before the results there’s a link to Zenodo where you can look at R files. 



<br>

## Data cleaning

Go back and review all the functions you have used in this course to clean data.

<br>

## Choosing the best visualisation

Go back and review all the graphs or other figures you have used in this course.

<br>

## Downloading data

Practice downloading datasets from the internet for the assignment using the Assessment Guidelines on Minerva.

<br>