<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BLGY5121M Adv Stats - Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BLGY5121M Adv Stats</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Advanced Statistics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./aiandgraphs.html">
 <span class="menu-text">Graphs and AI</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./lm.html" aria-current="page">
 <span class="menu-text">Linear Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./power.html">
 <span class="menu-text">Power Analyses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./multivariatemethods.html">
 <span class="menu-text">Multivariate Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mixedmodels1.html">
 <span class="menu-text">Mixed Models 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mixedmodels2.html">
 <span class="menu-text">Mixed Models 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./spatial.html">
 <span class="menu-text">Spatial Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./metaanalyses.html">
 <span class="menu-text">Meta-analyses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./finally.html">
 <span class="menu-text">Finally</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#continuous-response-continuous-predictor-regression" id="toc-continuous-response-continuous-predictor-regression" class="nav-link active" data-scroll-target="#continuous-response-continuous-predictor-regression">Continuous Response, Continuous Predictor (Regression)</a>
  <ul class="collapse">
  <li><a href="#running-the-analysis" id="toc-running-the-analysis" class="nav-link" data-scroll-target="#running-the-analysis">Running the analysis</a></li>
  <li><a href="#what-has-lm-just-done" id="toc-what-has-lm-just-done" class="nav-link" data-scroll-target="#what-has-lm-just-done">What has lm just done?</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results">Interpreting the results</a>
  <ul class="collapse">
  <li><a href="#assumptions-to-check" id="toc-assumptions-to-check" class="nav-link" data-scroll-target="#assumptions-to-check">Assumptions to check</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#continuous-response-one-predictor-with-two-categories-t-test" id="toc-continuous-response-one-predictor-with-two-categories-t-test" class="nav-link" data-scroll-target="#continuous-response-one-predictor-with-two-categories-t-test">Continuous Response, One Predictor with Two Categories (t test)</a>
  <ul class="collapse">
  <li><a href="#visualising-data" id="toc-visualising-data" class="nav-link" data-scroll-target="#visualising-data">Visualising data</a></li>
  <li><a href="#fitting-a-model" id="toc-fitting-a-model" class="nav-link" data-scroll-target="#fitting-a-model">Fitting a model</a></li>
  </ul></li>
  <li><a href="#continuous-response-one-predictor-with-three-or-more-categories-anova" id="toc-continuous-response-one-predictor-with-three-or-more-categories-anova" class="nav-link" data-scroll-target="#continuous-response-one-predictor-with-three-or-more-categories-anova">Continuous Response, One Predictor with Three or More Categories (ANOVA)</a>
  <ul class="collapse">
  <li><a href="#running-the-analysis-1" id="toc-running-the-analysis-1" class="nav-link" data-scroll-target="#running-the-analysis-1">Running the analysis</a></li>
  <li><a href="#assumptions-to-check-1" id="toc-assumptions-to-check-1" class="nav-link" data-scroll-target="#assumptions-to-check-1">Assumptions to check</a></li>
  <li><a href="#interpreting-the-results-1" id="toc-interpreting-the-results-1" class="nav-link" data-scroll-target="#interpreting-the-results-1">Interpreting the results</a></li>
  </ul></li>
  <li><a href="#generalised-linear-models" id="toc-generalised-linear-models" class="nav-link" data-scroll-target="#generalised-linear-models">Generalised Linear Models</a></li>
  <li><a href="#binomial-response" id="toc-binomial-response" class="nav-link" data-scroll-target="#binomial-response">Binomial Response</a>
  <ul class="collapse">
  <li><a href="#running-the-analysis-2" id="toc-running-the-analysis-2" class="nav-link" data-scroll-target="#running-the-analysis-2">Running the analysis</a></li>
  <li><a href="#assumptions-to-check-2" id="toc-assumptions-to-check-2" class="nav-link" data-scroll-target="#assumptions-to-check-2">Assumptions to check</a></li>
  <li><a href="#interpreting-the-results-2" id="toc-interpreting-the-results-2" class="nav-link" data-scroll-target="#interpreting-the-results-2">Interpreting the results</a></li>
  <li><a href="#communicating-the-results" id="toc-communicating-the-results" class="nav-link" data-scroll-target="#communicating-the-results">Communicating the results</a></li>
  </ul></li>
  <li><a href="#count-response" id="toc-count-response" class="nav-link" data-scroll-target="#count-response">Count Response</a>
  <ul class="collapse">
  <li><a href="#running-the-analysis-3" id="toc-running-the-analysis-3" class="nav-link" data-scroll-target="#running-the-analysis-3">Running the analysis</a></li>
  <li><a href="#assumptions-to-check-3" id="toc-assumptions-to-check-3" class="nav-link" data-scroll-target="#assumptions-to-check-3">Assumptions to check</a></li>
  <li><a href="#interpreting-the-results-3" id="toc-interpreting-the-results-3" class="nav-link" data-scroll-target="#interpreting-the-results-3">Interpreting the results</a></li>
  <li><a href="#communicating-the-results-1" id="toc-communicating-the-results-1" class="nav-link" data-scroll-target="#communicating-the-results-1">Communicating the results</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Linear models can be used to run regressions (where the response and predictor are both continuous) or t-tests and ANOVAs (where the response is continuous and the predictor is a factor.)</p>
<button type="button" class="btn btn-success">
Alternative terminology - another name for a response is the dependent variable. Predictors are sometimes called explanatory, independent variables or factors.
</button>
<p><br></p>
<section id="continuous-response-continuous-predictor-regression" class="level1">
<h1>Continuous Response, Continuous Predictor (Regression)</h1>
<p>A regression is just a special case of a linear model, where both the response and predictor variables are continuous.</p>
<p>The relationship between a response (also called dependent) variable <span class="math inline">\(y\)</span> and one or more predictor variables <span class="math inline">\(x_{1}\)</span>,<span class="math inline">\(x_{2}\)</span>…<span class="math inline">\(x_{n}\)</span> is modelled. For example, we could use linear regression to test whether temperature (the predictor variable) effects plant height (the response variable).</p>
<p><img src="./img/Linear_regression_image.jpg" class="img-fluid" alt="green plants including lots of ferns in a forest"></p>
<p><br> Follow this link to a data set on plant heights around the world, <a href="./data/Plant_height.csv">Plant_height.csv</a>. Right click to “Save as” in your Rproj <code>data</code> folder and import into R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Plant_height <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/Plant_height.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>It is useful to first visualise our data. For two continuous variables use a scatterplot. <code>loght</code> is log of height. <code>temp</code> is temperature.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> temp, <span class="at">y =</span> loght), <span class="at">data =</span> Plant_height) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<section id="running-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="running-the-analysis">Running the analysis</h2>
<p>In R you can fit linear models using the function <code>lm</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(loght <span class="sc">~</span> temp, <span class="at">data =</span> Plant_height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The response variable <code>loght</code> goes before the tilde. After the tilde we list the predictor variables, only <code>temp</code> in this case.</p>
<p>The <code>data =</code> argument specifies the data frame from which the variables will be taken.</p>
<p><br></p>
<p>To obtain detailed output (e.g., coefficient values, R<sup>2</sup>, test statistics, <em>p</em>-values, confidence intervals etc.), assign the output of the <code>lm</code> function to a new object in R. Then pass that new model object through the <code>summary</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(loght <span class="sc">~</span> temp, <span class="at">data =</span> Plant_height)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = loght ~ temp, data = Plant_height)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.97903 -0.42804 -0.00918  0.43200  1.79893 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.225665   0.103776  -2.175    0.031 *  
temp         0.042414   0.005593   7.583 1.87e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6848 on 176 degrees of freedom
Multiple R-squared:  0.2463,    Adjusted R-squared:  0.242 
F-statistic:  57.5 on 1 and 176 DF,  p-value: 1.868e-12</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="what-has-lm-just-done" class="level2">
<h2 class="anchored" data-anchor-id="what-has-lm-just-done">What has lm just done?</h2>
<p>It has tried to make a line of best fit (the blue line in the graph).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The equation for that line is in the form <span class="math display">\[y = \alpha + \beta x \]</span></p>
<p><span class="math inline">\(\alpha\)</span> is the intercept (where the line crosses the y axis). <span class="math inline">\(\beta\)</span> is the slope. (This is the same as the equation for a straight line y = <strong>m</strong>x + <strong>c</strong> or y = <strong>a</strong>x + <strong>b</strong> you may have encountered before.)</p>
<p>The goal of lm is to obtain the best estimates for <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>. <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> are called the model coefficients.</p>
<p>To make it a model rather than just a straight line, it also has an extra bit called the error term <span class="math inline">\(\varepsilon\)</span>. You can think of this as how close the points are to the line. <span class="math inline">\(\varepsilon\)</span> is not usually reported as part of the equation. <span class="math display">\[y = \alpha + \beta x + \varepsilon \]</span></p>
<p><br></p>
</section>
<section id="interpreting-the-results" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-results">Interpreting the results</h2>
<p>The output given by <code>summary()</code> gives us the <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\alpha\)</span> coefficients so we can report the model equation <span class="math display">\[log(plant height) = -0.22566 +0.0421.temperature + \varepsilon \]</span></p>
<p>Look at the output to find where these numbers came from.</p>
<button type="button" class="btn btn-success">
Note that <span class="math inline">\(\beta\)</span> which is the slope can be interpreted as the amount of change in <span class="math inline">\(y\)</span> for each unit of <span class="math inline">\(x\)</span>. For example, as the temperature increases by 1 degree, the log(plant height) increases by 0.0241.
</button>
<p><br></p>
<p>Passing the model object through <code>summary()</code> also gives us the <em>t</em>-statistics and <em>p</em>-values related to each predictor. These test the null hypothesis that the true value for the coefficient is 0.</p>
<p>For the intercept we usually don’t care if it is zero or not, but for the other coefficient (the slope), a value significantly differing from zero indicates that there is an association between that predictor and the response. In this example, temperature affects plant height.</p>
<p>Whilst the <em>t</em>-statistics and <em>p</em>-values indicate a significant association, the strength of the association is captured by the R<sup>2</sup> value. R<sup>2</sup> is the proportion of variance in the response that is explained by the predictor(s).</p>
<p>The <em>F</em>-statistic and associated <em>p</em>-value indicates whether the model as a whole is significant. The model will always be significant if any of the coefficients are significant. With only one predictor variable, the probability associated with the <em>t</em> test, that tests whether the slope differs from zero, is identical to the probability associated with the <em>F</em> statistic.</p>
<p>We can also obtain 95% confidence intervals for the two parameters. Checking that the intervals for the slope do not include zero is another way of showing that there is an association between the dependent and predictor variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %      97.5 %
(Intercept) -0.43047074 -0.02085828
temp         0.03137508  0.05345215</code></pre>
</div>
</div>
<p>In summary, you could report</p>
<blockquote class="blockquote">
<p>The model (log(plant height) = -0.22566 + 0.0421.temperature, R<sup>2</sup> = 0.246) was significant (F<sub>1,176</sub> = 57.5, p &lt; 0.001) with temperature significantly predicting (t = 7.583, p &lt; 0.001) the height of the plants. This means that when temperature increases by 1 degree the plant height increases by 0.042 (CI 0.031, 0.053).</p>
</blockquote>
<p>If you have run several analyses (or if there is more than one predictor), it may be useful to present the results as a table with coefficient values, standard errors and <em>p</em>-values for each explanatory variable. What parts you choose to report is down to discipline, style of the journal or what the writer thinks should be emphasised to answer the results question.</p>
<p><br></p>
<section id="assumptions-to-check" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-to-check">Assumptions to check</h3>
<p>But to have confidence in our results we should check the data met the assumptions.</p>
<p><strong>Independence</strong>. For all the data in these examples we’ll assume the observations are independent of each other.</p>
<button type="button" class="btn btn-success">
There are a variety of measures for dealing with non-independence. These include ensuring all important predictors are in the model; averaging across nested observations; or using a mixed-model (covered in another lesson).
</button>
<p><br></p>
<p><strong>Linearity</strong>. There is no point trying to fit a straight line to data that are curved!</p>
<p>Passing <code>model</code> through <code>plot()</code> gives four graphs. The first is a plot of residuals versus fitted values. Curvilinear relationships produce patterns in such plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The absence of strong patterning in the first plot indicates the assumption of linearity is valid.</p>
<p>Click <a href="https://gallery.shinyapps.io/slr_diag/">here</a> to see what patterns of residuals you would expect with curved relationships</p>
<p><br></p>
<p><strong>Constant variance</strong> If the plot of residuals versus fitted values is fan-shaped, the assumption of constant variance (homogeneity of variance) is violated.</p>
<p><br></p>
<p><strong>Normality</strong>. Checks of whether the data are normally distributed are usually performed by either plotting a histogram of the residuals or via a quantile plot where the residuals are plotted against the values expected from a normal distribution (the second of the figures obtained by <code>plot(model)</code>). If the points in the quantile plot lie mostly on the line, the residuals are normally distributed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(model<span class="sc">$</span>residuals) <span class="co"># Histogram of residuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">which =</span> <span class="dv">2</span>) <span class="co"># Quantile plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Problems with variance or normality can be addressed via transformations or by using a Generalised Linear Model, GLM. Note, however, that linear regression is reasonably robust against violations of constant variance and normality.</p>
<p><br></p>
<p><br></p>
</section>
</section>
</section>
<section id="continuous-response-one-predictor-with-two-categories-t-test" class="level1">
<h1>Continuous Response, One Predictor with Two Categories (t test)</h1>
<p>This is the same as running a t-test.</p>
<p>We could test if a sample of pH measurements from one river, A, differs from a sample of pH measurements from a second river, B. Save the data <a href="./data/River_pH.csv">River_pH.csv</a> in the <code>data</code> file in your Rproj.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>River_pH <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/River_pH.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualising-data" class="level2">
<h2 class="anchored" data-anchor-id="visualising-data">Visualising data</h2>
<p>We could plot a boxplot or bar chart with overlayed points. An alternative is a violin plot using <code>geom_violin</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> River_name, <span class="at">y =</span> pH), <span class="at">data =</span> River_pH) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Overlay the means and their 95% confidence intervals using <code>stat_summary()</code>. Change the axis labels using <code>xlab()</code> and <code>ylab()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> River_name, <span class="at">y =</span> pH), <span class="at">data =</span> River_pH) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"River"</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"pH of River"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<details>
<summary>
<strong>fun and fun.data explained</strong>
</summary>
<p><code>fun</code> and <code>fun.data</code> are arguments in <code>stat_summary()</code> that do statistical operations to data. <code>fun</code> takes the data and returns a single value such as the mean. <code>fun.data</code> calculates three values for each group: <code>y</code>, <code>ymin</code> and <code>ymax</code>. In our case, ymin is the lower confidence interval and ymax is the upper confidence interval.</p>
</details>
<p><br></p>
<p><strong>Challenge</strong></p>
<p>Read in the Palmer Penguins dataset (penguins.csv). Make a violin plot of <code>body_weight_g</code> for the two groups in <code>sex</code>.</p>
<p>Can you search the internet to find out how to remove NA values?</p>
<details>
<summary>
<strong>Solution</strong>
</summary>
<p>Read in the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/penguins.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Make a violin plot with mean, error bars, and axes labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> body_mass_g), <span class="at">data =</span> penguins) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Penguin Sex"</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>One solution (of many) to remove NA values is piping the data into the <code>drop_na()</code> function from the <code>tidyr</code> package. The resulting data can be piped into ggplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">drop_na</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Penguin Sex"</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</details>
<p><br></p>
</section>
<section id="fitting-a-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-a-model">Fitting a model</h2>
<p>As the previous example, use <code>lm()</code> and then put the resulting model through <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pH <span class="sc">~</span> River_name, <span class="at">data =</span> River_pH)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>lm()</code> has used the same equation but since our predictor is a factor/category oppose to numeric, how we interpret the results is different.</p>
<p>There are two groups - <code>A</code> and <code>B</code>. One is taken by the model as the <strong>baseline</strong> (<code>A</code>), the other as the contrast (<code>B</code>). The first level alphabetically is chosen by R as the baseline.</p>
<p>The intercept in the output is the estimated mean for the baseline, i.e.&nbsp;for River A. The <code>B</code> estimate is the estimated mean difference in <code>pH</code> between River A and B. We can therefore write the equation for this model as:</p>
<p><span class="math display">\[pH = 8.6615 -2.2529 \times x\]</span> where <span class="math inline">\(x = 1\)</span> if the river is river B or <span class="math inline">\(x = 0\)</span> if it is the baseline river A.</p>
<p>We could report: There is a significant difference in pH between river A (mean = 8.66) and river B (mean = 6.41; t = -6.98, p &lt; 0.001).</p>
<details>
<summary>
<strong>Are these results the same as running a t test?</strong>
</summary>
<p>Yes! Same t and p values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pH <span class="sc">~</span> River_name, <span class="at">data =</span> River_pH, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  pH by River_name
t = 6.9788, df = 18, p-value = 1.618e-06
alternative hypothesis: true difference in means between group A and group B is not equal to 0
95 percent confidence interval:
 1.574706 2.931168
sample estimates:
mean in group A mean in group B 
       8.661497        6.408560 </code></pre>
</div>
</div>
</details>
<p><br></p>
<p><strong>Challenge</strong></p>
<p>Run a model and report if there is an effect of <code>sex</code> on the <code>body_mass_g</code> of penguins.</p>
<details>
<summary>
<strong>Solution</strong>
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> sex, <span class="at">data =</span> penguins)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is a significant effect of sex on penguin body mass with males larger (mean = 4545.68g) than females (mean = 3862.27g; t = 8.54, p &lt; 0.001).</p>
</details>
<p><br></p>
<p><strong>Challenge</strong></p>
<p>Check the assumptions of the penguin sex model using plot.</p>
<p>Do you think it meets the assumptions?</p>
<details>
<summary>
<strong>Solution</strong>
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A linear relationship is not relevant here as the predictor is categorical not numeric. Something is wrong with the normality of the residuals. This would alert us to some other variable effecting the data - in this case penguin species. The variance might be greater in males than females.</p>
</details>
<p><br></p>
</section>
</section>
<section id="continuous-response-one-predictor-with-three-or-more-categories-anova" class="level1">
<h1>Continuous Response, One Predictor with Three or More Categories (ANOVA)</h1>
<p><img src="./img/ANOVA_single_factor_image.png" class="img-fluid" alt="aerial view of baby turtles on a beach"></p>
<p>For this example, compare hatching times of turtle eggs (continuous response) incubated at four different temperatures - 15°C, 20°C, 25°C and 30°C (categorical predictor with four levels).</p>
<button type="button" class="btn btn-success">
Note that an ANOVA is a linear model, just like linear regression except that the predictor variables are categorical rather than continuous.
</button>
<p><br></p>
<p>The model fits four numbers to describe the mean response of each temperature (rather than just a single intercept and single slope in a simple linear regression).</p>
<details>
<summary>
<strong>Equation</strong>
</summary>
<p>For this example, our linear model equation will have this form:</p>
<p><span class="math display">\[HatchingTime = \mu + \beta_1.Temp_{15} + \beta_2.Temp_{20} + \beta_3.Temp_{25} + \beta_4.Temp_{30} + \varepsilon\]</span> Where <span class="math display">\[\mu\]</span> is the overall mean. <span class="math display">\[\beta\]</span> are the numbers (coefficients) for each of the temperatures.</p>
</details>
<p><br></p>
<section id="running-the-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="running-the-analysis-1">Running the analysis</h2>
<p>Save the turtle hatching data, <a href="./data/Turtles.csv">Turtles.csv</a>, import into R and check the temperature variable is a factor with the <code>str</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>Turtles <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/Turtles.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Turtles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   40 obs. of  2 variables:
 $ Temperature: int  15 15 15 15 15 15 15 15 15 15 ...
 $ Days       : int  37 43 45 54 56 65 62 73 74 75 ...</code></pre>
</div>
</div>
<p>R is treating Temperature as a numeric (int means integer). We need to change that variable to become a factor (categories).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>Turtles<span class="sc">$</span>Temperature <span class="ot">&lt;-</span> <span class="fu">factor</span>(Turtles<span class="sc">$</span>Temperature)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now run the model using <code>lm</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>turtle_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Days <span class="sc">~</span> Temperature, <span class="at">data =</span> Turtles)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(turtle_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Days ~ Temperature, data = Turtles)

Residuals:
    Min      1Q  Median      3Q     Max 
-28.200  -9.225   1.650   9.025  19.400 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     58.400      4.092  14.273  &lt; 2e-16 ***
Temperature20  -13.800      5.787  -2.385   0.0225 *  
Temperature25   -9.200      5.787  -1.590   0.1206    
Temperature30  -38.300      5.787  -6.619 1.04e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.94 on 36 degrees of freedom
Multiple R-squared:  0.5711,    Adjusted R-squared:  0.5354 
F-statistic: 15.98 on 3 and 36 DF,  p-value: 9.082e-07</code></pre>
</div>
</div>
<p><br></p>
<p>If we thought we needed a post hoc test we could pass our model object through <code>emmeans()</code> from <code>emmeans</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(turtle_model, pairwise <span class="sc">~</span> Temperature)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Temperature emmean   SE df lower.CL upper.CL
 15            58.4 4.09 36     50.1     66.7
 20            44.6 4.09 36     36.3     52.9
 25            49.2 4.09 36     40.9     57.5
 30            20.1 4.09 36     11.8     28.4

Confidence level used: 0.95 

$contrasts
 contrast                      estimate   SE df t.ratio p.value
 Temperature15 - Temperature20     13.8 5.79 36   2.385  0.0983
 Temperature15 - Temperature25      9.2 5.79 36   1.590  0.3970
 Temperature15 - Temperature30     38.3 5.79 36   6.619  &lt;.0001
 Temperature20 - Temperature25     -4.6 5.79 36  -0.795  0.8563
 Temperature20 - Temperature30     24.5 5.79 36   4.234  0.0008
 Temperature25 - Temperature30     29.1 5.79 36   5.029  0.0001

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="assumptions-to-check-1" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-to-check-1">Assumptions to check</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(turtle_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(turtle_model<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-24-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Remember: the first graph produced by <code>plot()</code>, tells us about homogeneity of variance (equal variance). Look for an even spread of the residuals on the <em>y</em> axis for each of the levels on the <em>x</em> axis.</p>
<p>The second plot and the histogram from <code>hist()</code> tells us about normality.</p>
<p><br></p>
</section>
<section id="interpreting-the-results-1" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-results-1">Interpreting the results</h2>
<p><strong>Challenge</strong></p>
<p>Given the output, write out how you could report these results. There will be many ways.</p>
<p>Hint: Look at how we reported the examples before. Look at how a paper in your discipline reported results. Look at how ANOVA is reported.</p>
<p><br></p>
<p><strong>Challenge</strong></p>
<p>Run a lm model to test the effect of penguin <code>species</code> on <code>body_mass_g</code>. Report the results.</p>
<p><br></p>
<button type="button" class="btn btn-success">
You might have previously been taught to run an anova and post hoc Tukey test on continuous data with 3 or more factors. If you run those tests using the code below you get the same result.
</button>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>Turtle_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Days <span class="sc">~</span> Temperature, <span class="at">data =</span> Turtles)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Turtle_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Temperature  3   8025  2675.2   15.98 9.08e-07 ***
Residuals   36   6027   167.4                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(Turtle_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Days ~ Temperature, data = Turtles)

$Temperature
       diff       lwr        upr     p adj
20-15 -13.8 -29.38469   1.784689 0.0982694
25-15  -9.2 -24.78469   6.384689 0.3969971
30-15 -38.3 -53.88469 -22.715311 0.0000006
25-20   4.6 -10.98469  20.184689 0.8562615
30-20 -24.5 -40.08469  -8.915311 0.0008384
30-25 -29.1 -44.68469 -13.515311 0.0000785</code></pre>
</div>
</div>
<p><br></p>
<p><br></p>
</section>
</section>
<section id="generalised-linear-models" class="level1">
<h1>Generalised Linear Models</h1>
<p>If you understand general linear models then you can understand more complex generalised linear models. <strong>General</strong> linear models are used when the response (dependent) is <strong>continuous</strong>. Whereas <strong>generalised</strong> linear models are used when the response variable is not continuous but <strong>binary</strong> or <strong>count</strong> or <strong>proportional</strong> data.</p>
<p>Generalised linear models need link functions. In simple terms, these vary with the type of data the response is and dictate how the generalised linear model is fitted. For example, for binomial data the link function is <code>logit()</code> and for count data it’s <code>log()</code>. We specify the link function using the argument <code>family =</code> within the <code>glm()</code>.</p>
<p><br></p>
</section>
<section id="binomial-response" class="level1">
<h1>Binomial Response</h1>
<p><img src="./img/GLM1_binary_image.jpg" class="img-fluid" alt="three brown crabs around rocks"></p>
<p>Save this <a href="./data/crabs.csv">crabs.csv</a> and read into R. The <code>CrabPres</code> column is whether a crab was present in that area of the beach surveyed. This response variable is binomial: the presence or absence of a crab.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>crabs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/crabs.csv"</span>, <span class="at">header =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We use the functions <code>str</code> and <code>table</code> to check the type of data. Plus how many levels there are in the variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(crabs)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(crabs<span class="sc">$</span>Dist) <span class="co"># shows n for each level too</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(crabs<span class="sc">$</span>Time)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(crabs<span class="sc">$</span>CrabPres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can make sure R thinks <code>Time</code> is a factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>crabs<span class="sc">$</span>Time <span class="ot">&lt;-</span> <span class="fu">factor</span>(crabs<span class="sc">$</span>Time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<section id="running-the-analysis-2" class="level2">
<h2 class="anchored" data-anchor-id="running-the-analysis-2">Running the analysis</h2>
<p>We can fit a model to test whether the probability of crab presence changes with time (a factor) and distance (a continuous variable).</p>
<p>The response variable (presence/absence of crabs) is binomial, so we use <code>family=binomial</code> in the glm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>crab_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(CrabPres <span class="sc">~</span> Time <span class="sc">*</span> Dist, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> crabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="assumptions-to-check-2" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-to-check-2">Assumptions to check</h2>
<p><strong>Assumption - There is a straight line relationship between the logit function of the mean of <span class="math inline">\(y\)</span> and the predictors <span class="math inline">\(x\)</span></strong></p>
<p>For this assumption, we check the residual plot for non-linearity, or a U-shape.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(crab_glm, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Unfortunately, passing the <code>glm</code> object through the plot function gives us a very odd looking plot due to the discreteness of the data (i.e., many points on top of each other).</p>
<p>For a more useful plot we can instead fit the model using the <code>manyglm()</code> function in the <code>mvabund</code> package.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mvabund)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>crab_manyglm <span class="ot">&lt;-</span> <span class="fu">manyglm</span>(CrabPres <span class="sc">~</span> Time <span class="sc">*</span> Dist, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> crabs)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(crab_manyglm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In our case there is no evidence of non-linearity.</p>
<p>If the residuals seem to go down then up, or up then down, we may need to add a polynomial function of the predictors using the <code>poly</code> function.</p>
<p><br></p>
</section>
<section id="interpreting-the-results-2" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-results-2">Interpreting the results</h2>
<p>For binomial models in particular the p-values from the <code>summary</code> function are not reliable, and we prefer to use the <code>anova</code> function to see if predictors are significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crab_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = CrabPres ~ Time * Dist, family = "binomial", data = crabs)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -1.71431    0.68664  -2.497   0.0125 *
Time10       1.29173    0.87194   1.481   0.1385  
Dist         0.02522    0.11137   0.226   0.8208  
Time10:Dist  0.05715    0.14149   0.404   0.6863  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 71.097  on 56  degrees of freedom
Residual deviance: 63.466  on 53  degrees of freedom
AIC: 71.466

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(crab_glm, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: CrabPres

Terms added sequentially (first to last)

          Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)   
NULL                         56     71.097            
Time       1   6.6701        55     64.427 0.009804 **
Dist       1   0.7955        54     63.631 0.372448   
Time:Dist  1   0.1647        53     63.466 0.684852   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value for <code>Time</code> is P&lt;0.01 so we conclude there is an effect of time on the presence of crabs, but no effect of distance or interaction between time and distance.</p>
<details>
<summary>
<strong>anova results</strong>
</summary>
<p>When there is more than one predictor, the maths ANOVA uses can be done in three different ways. These ways are named type I, II and III. This <a href="https://www.r-bloggers.com/2011/03/anova-%E2%80%93-type-iiiiii-ss-explained/">R bloggers article</a> explains the differences.</p>
<p>Our crab example is approximately balanced (even sample numbers in each group) so whatever version of ANOVA R uses we’ll get the same results. However, if you have unbalanced data you could compare differences among type I, II and III ANOVAs using the function <code>Anova()</code> in the <code>car</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm_model) <span class="co"># default is type 1</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(lm_model, <span class="at">type =</span> <span class="dv">2</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(lm_model, <span class="at">type =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</details>
<p><br></p>
<button type="button" class="btn btn-success">
<p>This sample is reasonably large, so these p-values should be a good approximation. For a small sample it is often better to use resampling to calculate p-values. When you use <kbd><code>manyglm</code></kbd> the <kbd><code>summary</code></kbd> and <kbd><code>anova</code></kbd> functions use resampling by default.</p>
In this case the results are quite similar, but in small samples it can often make a big difference.
</button>
<p><br></p>
<details>
<summary>
<strong>Optimising the model</strong>
</summary>
<p>When there is more than one predictor you can try reducing the model by removing predictors and comparing models. We can use a number called the AIC to compare. Lower AICs are better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(crab_glm, <span class="at">test =</span> <span class="st">"Chi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=71.47
CrabPres ~ Time * Dist

            Df Deviance    AIC     LRT Pr(&gt;Chi)
- Time:Dist  1   63.631 69.631 0.16472   0.6849
&lt;none&gt;           63.466 71.466                 

Step:  AIC=69.63
CrabPres ~ Time + Dist

       Df Deviance    AIC    LRT Pr(&gt;Chi)   
- Dist  1   64.427 68.427 0.7955  0.37245   
&lt;none&gt;      63.631 69.631                   
- Time  1   70.275 74.275 6.6438  0.00995 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=68.43
CrabPres ~ Time

       Df Deviance    AIC    LRT Pr(&gt;Chi)   
&lt;none&gt;      64.427 68.427                   
- Time  1   71.097 73.097 6.6701 0.009804 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = CrabPres ~ Time, family = "binomial", data = crabs)

Coefficients:
(Intercept)       Time10  
     -1.609        1.535  

Degrees of Freedom: 56 Total (i.e. Null);  55 Residual
Null Deviance:      71.1 
Residual Deviance: 64.43    AIC: 68.43</code></pre>
</div>
</div>
<p><code>step()</code> removes the interaction (Dist * Time), then <code>Dist</code> and the AIC improves (gets lower). This confirms they are not predictors of the response.</p>
</details>
<p><br></p>
</section>
<section id="communicating-the-results" class="level2">
<h2 class="anchored" data-anchor-id="communicating-the-results">Communicating the results</h2>
<p>You can use the p values to report results like in other tests, e.g., “There is strong evidence that the presence of crabs varies with time (p = 0.01).” For multiple predictors it’s best to display the results in a table.</p>
<p><br></p>
<button type="button" class="btn btn-success">
Tip: People get stuck interpreting binomial results because they do not have a clear idea of what the baseline (reference) groups are in their models. In this example we would ensure we know that baseline for the response <kbd><code>CrabPres</code></kbd> is <strong>absence</strong> of crabs and baseline for <kbd><code>Time</code></kbd> is time point <strong>5</strong>.
</button>
<p><br></p>
<p>The coefficients for the intercept is the value of the response variable (on a logit scale) when the factor predictors (<code>Time</code> in our example) is the baseline (time point 5 in our example) and the numeric predictors (<code>Dist</code>) is 0. The coefficient for <code>Time</code> (a factor) tells us the difference in the response between the baseline and the other group of the factor (the difference between time point 5 and time point 10).</p>
<p>The coefficients for numeric predictors can show negative or positive relationships with the response.</p>
<p>The coefficient numbers (called log odds) are difficult for you (and your readers) to interpret. Many people convert them into effect sizes called <strong>odds ratios</strong> to report them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(crab_glm)) <span class="co"># calculates the exponential of the coefficients in the model i.e. turns log odds into odds ratios</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      Time10        Dist Time10:Dist 
  0.1800871   3.6390656   1.0255455   1.0588183 </code></pre>
</div>
</div>
<p>Odds ratios above 1 mean crabs are more likely to be present (present is coded as 1 in the response <code>CrabPres</code>). Odds ratios below 1 mean crabs are less likely to be present.</p>
<p>The odds ratio for <code>Time</code> is 3.6. We report “Crabs are 3.6 times more likely to be present at time point 10 compared to time point 5”.</p>
<button type="button" class="btn btn-success">
Tip if the odds ratio is below 1 try recoding the explanatory variables so that another group is the baseline.
</button>
<p><br></p>
<p>For numeric predictors a positive odds ratio such as 3.21 would mean that a 1 unit increase in the predictor, increases the odds of the response being present by 3.21. However, our odds ratio for distance is negative which is more difficult to put into words and relate back to the research question. One solution is to express it as the % decrease. For example, (0.97–1) * 100 = -3%. Then we can write “Each additional increase of one in distance is associated with an 3% decrease in the odds of a crab being present.</p>
<p><strong>Challenge</strong></p>
<p>What plots do you think could be used to present this data?</p>
<p><br></p>
<p><br></p>
</section>
</section>
<section id="count-response" class="level1">
<h1>Count Response</h1>
<section id="running-the-analysis-3" class="level2">
<h2 class="anchored" data-anchor-id="running-the-analysis-3">Running the analysis</h2>
<p><img src="./img/GLM2_counts_image.jpg" class="img-fluid" alt="a close up photograph of a snail"></p>
<p>This example has counts of different animal groups at control sites and sites where bush regeneration has been carried out (treatment). We will use only one group of animals - slugs (Soleolifera is the order name of terrestrial slugs) to see if the the bush regeneration activities have affected slug abundance.</p>
<p>Save <a href="./data/revegetation.csv">revegetation.csv</a> and import into R and view the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>reveg <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/revegetation.csv"</span>, <span class="at">header =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you view the frequency histogram of the slug counts, you will see that it is very skewed, with many small values and few large counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(reveg<span class="sc">$</span>Soleolifera)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="500"></p>
</div>
</div>
<button type="button" class="btn btn-success">
The default distribution for count data is the Poisson. The Poisson distribution assumes the variance equals the mean. This is quite a restrictive assumption which ecological count data often violates. We may need to use the more flexible <strong>negative-binomial</strong> distribution instead.
</button>
<p><br></p>
<p>We can use a GLM to test whether the counts of slugs (from the order Soleolifera) differ between control and regenerated sites. To fit the GLM, we will use the <code>manyglm</code> function instead of <code>glm</code> so we have access to more useful residual plots.</p>
<p>To fit the GLM, load the mvabund package then fit the following model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mvabund)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>slug_glm <span class="ot">&lt;-</span> <span class="fu">manyglm</span>(Soleolifera <span class="sc">~</span> Treatment, <span class="at">family =</span> <span class="st">"poisson"</span>, <span class="at">data =</span> reveg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Treatment is the predictor variable with two levels, control and revegetated.</p>
<p><br></p>
</section>
<section id="assumptions-to-check-3" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-to-check-3">Assumptions to check</h2>
<p>Before looking at the results, look at the residual plot to check the assumptions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(slug_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="500"></p>
</div>
</div>
<p>It’s hard to say whether there is any non-linearity in this plot, this is because the predictor is binary (control vs revegetated).</p>
<p>Looking at the mean-variance assumption, it does appear as though there is a fan shape. The residuals are more spread out on the right than the left - we call this <strong>overdispersion</strong>.</p>
<p>This tells us the mean-variance assumption of the Poisson is probably violated. We should try a different distribution. We can instead fit a negative-binomial distribution in <code>manyglm</code> by changing the family argument to <code>family="negative binomial"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>slug_glm2 <span class="ot">&lt;-</span> <span class="fu">manyglm</span>(Soleolifera <span class="sc">~</span> Treatment, <span class="at">family =</span> <span class="st">"negative binomial"</span>, <span class="at">data =</span> reveg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Look again at the residual plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(slug_glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="500"></p>
</div>
</div>
<p>This seems to have improved the residual plot. There is no longer a strong fan shape, so we can go ahead and look at the results.</p>
<p><br></p>
</section>
<section id="interpreting-the-results-3" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-results-3">Interpreting the results</h2>
<p>We can use <code>summary</code> and <code>anova</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(slug_glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time elapsed: 0 hr 0 min 0 sec</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: Soleolifera ~ Treatment

Multivariate test:
            Res.Df Df.diff   Dev Pr(&gt;Dev)   
(Intercept)     48                          
Treatment       47       1 10.52    0.004 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Arguments: P-value calculated using 999 iterations via PIT-trap resampling.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slug_glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Test statistics:
                     wald value Pr(&gt;wald)    
(Intercept)               1.502     0.030 *  
TreatmentRevegetated      3.307     0.001 ***
--- 
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Test statistic:  3.307, p-value: 0.001 
Arguments: P-value calculated using 999 resampling iterations via pit.trap resampling.</code></pre>
</div>
</div>
<p>Both tests indicate treatment has an effect (p&lt;0.01).</p>
<p><br></p>
</section>
<section id="communicating-the-results-1" class="level2">
<h2 class="anchored" data-anchor-id="communicating-the-results-1">Communicating the results</h2>
<p>You could write “There is strong evidence of a positive effect of bush regeneration on the abundance of slugs from the order Soleolifera (p &lt; 0.01)”. For multiple predictors it’s best to display the results in a table.</p>
<p>You should also indicate which distribution was used (e.g.&nbsp;negative-binomial) and if resampling was used. “We used a negative-binomial generalised linear model due to overdispersion evident in the data. Bootstrap resampling was used with 1000 resamples” (1000 is the default when using <code>manyglm()</code>).</p>
<p><strong>Challenge</strong></p>
<p>What graph could be used to visualise the differences in slug counts between control and revegetated sites.</p>
<details>
<summary>
<strong>Solution</strong>
</summary>
<p>There are various solutions. Boxplot is one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Soleolifera <span class="sc">~</span> Treatment, <span class="at">ylab =</span> <span class="st">"Count"</span>, <span class="at">xlab =</span> <span class="st">"Treatment"</span>, <span class="at">data =</span> reveg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lm_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="500"></p>
</div>
</div>
</details>
<p><br></p>
<p><br></p>
<p>Adapted from <a href="https://github.com/nicercode/EnvironmentalComputing">EnvironmentalComputing</a> and Herman et al., 2021 <a href="https://carpentries-incubator.github.io/simple-linear-regression-public-health/">Statistical Analysis for Public Health: Simple linear regression</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><a href="https://creativecommons.org/">CC Licensed</a></div>   
    <div class="nav-footer-right"><a href="https://github.com/acriach/BLGY5121MAdvStats">Source</a></div>
  </div>
</footer>



</body></html>