<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BLGY5121M Adv Stats - Meta-analyses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BLGY5121M Adv Stats</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Advanced Statistics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./aiandgraphs.html">
 <span class="menu-text">Graphs and AI</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lm.html">
 <span class="menu-text">Linear Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./power.html">
 <span class="menu-text">Power Analyses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./multivariatemethods.html">
 <span class="menu-text">Multivariate Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mixedmodels1.html">
 <span class="menu-text">Mixed Models 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mixedmodels2.html">
 <span class="menu-text">Mixed Models 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./spatial.html">
 <span class="menu-text">Spatial Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./metaanalyses.html" aria-current="page">
 <span class="menu-text">Meta-analyses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./finally.html">
 <span class="menu-text">Finally</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#calculating-effect-sizes" id="toc-calculating-effect-sizes" class="nav-link active" data-scroll-target="#calculating-effect-sizes">Calculating effect sizes</a>
  <ul class="collapse">
  <li><a href="#metafor-for-meta-analysis" id="toc-metafor-for-meta-analysis" class="nav-link" data-scroll-target="#metafor-for-meta-analysis"><code>Metafor</code> for meta-analysis</a></li>
  <li><a href="#calculating-standardized-effect-sizes" id="toc-calculating-standardized-effect-sizes" class="nav-link" data-scroll-target="#calculating-standardized-effect-sizes">Calculating ‘standardized’ effect sizes</a></li>
  <li><a href="#forest-plots" id="toc-forest-plots" class="nav-link" data-scroll-target="#forest-plots">Forest Plots</a></li>
  </ul></li>
  <li><a href="#calculating-the-overall-effect-size" id="toc-calculating-the-overall-effect-size" class="nav-link" data-scroll-target="#calculating-the-overall-effect-size">Calculating the overall effect size</a>
  <ul class="collapse">
  <li><a href="#common-effect-model" id="toc-common-effect-model" class="nav-link" data-scroll-target="#common-effect-model">Common-effect model</a></li>
  <li><a href="#random-effects-model" id="toc-random-effects-model" class="nav-link" data-scroll-target="#random-effects-model">Random-effects model</a></li>
  <li><a href="#running-a-common-effect-model" id="toc-running-a-common-effect-model" class="nav-link" data-scroll-target="#running-a-common-effect-model">Running a common-effect model</a></li>
  <li><a href="#running-a-random-effects-model" id="toc-running-a-random-effects-model" class="nav-link" data-scroll-target="#running-a-random-effects-model">Running a random-effects model</a></li>
  <li><a href="#understanding-heterogeneity" id="toc-understanding-heterogeneity" class="nav-link" data-scroll-target="#understanding-heterogeneity">Understanding heterogeneity</a></li>
  </ul></li>
  <li><a href="#meta-regression-the-random-effects-model" id="toc-meta-regression-the-random-effects-model" class="nav-link" data-scroll-target="#meta-regression-the-random-effects-model">Meta-regression (the random-effects model)</a></li>
  <li><a href="#checking-for-publication-bias" id="toc-checking-for-publication-bias" class="nav-link" data-scroll-target="#checking-for-publication-bias">Checking for publication bias</a>
  <ul class="collapse">
  <li><a href="#funnel-plot" id="toc-funnel-plot" class="nav-link" data-scroll-target="#funnel-plot">Funnel plot</a></li>
  <li><a href="#eggers-test" id="toc-eggers-test" class="nav-link" data-scroll-target="#eggers-test">Egger’s test</a></li>
  <li><a href="#trim-and-fill" id="toc-trim-and-fill" class="nav-link" data-scroll-target="#trim-and-fill">Trim-and-fill</a></li>
  </ul></li>
  <li><a href="#challenges" id="toc-challenges" class="nav-link" data-scroll-target="#challenges">Challenges</a></li>
  <li><a href="#further-help-and-references" id="toc-further-help-and-references" class="nav-link" data-scroll-target="#further-help-and-references">Further help and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Meta-analyses</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><img src="./img/metanalysis.jpg" class="img-fluid" alt="Two diagrams. Left diagram has three silouhettes of insects above a graph with four horizontal lines with points in the middle of each labbelled female, male mixed sex and hermaphrodite. None of the four lines overlap the reference vertical dotted line. Right diagram has seven silouhettes of insects above a graph with four horizontal lines with points in the middle of each labbelled female, male mixed sex and hermaphrodite. On this graph all four lines overlap the reference vertical dotted line."></p>
<p>There are many steps involve in a meta-analysis. For guidance on how to do a meta-analysis see <a href="https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-017-0357-7">(Nakagawa <em>et al.</em> 2017)</a> which considers the process of meta-analysis using 10 questions.</p>
<p>This lesson only considers how to do the statistics part of the meta-analysis &amp; publication bias.</p>
<p><br></p>
<section id="calculating-effect-sizes" class="level1">
<h1>Calculating effect sizes</h1>
<section id="metafor-for-meta-analysis" class="level2">
<h2 class="anchored" data-anchor-id="metafor-for-meta-analysis"><code>Metafor</code> for meta-analysis</h2>
<p>First, install and load the <code>metafor</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>Have a look at the data set named <code>dat.curtis1998</code> included in the package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat.curtis1998</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   102 obs. of  20 variables:
 $ id      : int  21 22 27 32 35 38 44 63 86 87 ...
 $ paper   : int  44 44 121 121 121 121 159 183 209 209 ...
 $ genus   : chr  "ALNUS" "ALNUS" "ACER" "QUERCUS" ...
 $ species : chr  "RUBRA" "RUBRA" "RUBRUM" "PRINUS" ...
 $ fungrp  : chr  "N2FIX" "N2FIX" "ANGIO" "ANGIO" ...
 $ co2.ambi: num  350 350 350 350 350 350 350 395 350 350 ...
 $ co2.elev: num  650 650 700 700 700 700 700 795 700 700 ...
 $ units   : chr  "ul/l" "ul/l" "ppm" "ppm" ...
 $ time    : int  47 47 59 70 64 50 730 365 365 365 ...
 $ pot     : chr  "0.5" "0.5" "2.6" "2.6" ...
 $ method  : chr  "GC" "GC" "GH" "GH" ...
 $ stock   : chr  "SEED" "SEED" "SEED" "SEED" ...
 $ xtrt    : chr  "FERT" "FERT" "NONE" "NONE" ...
 $ level   : chr  "HIGH" "CONTROL" "." "." ...
 $ m1i     : num  6.82 2.6 2.99 5.91 4.61 ...
 $ sd1i    : num  1.77 0.667 0.856 1.742 1.407 ...
 $ n1i     : int  3 5 5 5 4 5 3 3 20 16 ...
 $ m2i     : num  3.94 2.25 1.93 6.62 4.1 ...
 $ sd2i    : num  1.116 0.328 0.552 1.631 1.257 ...
 $ n2i     : int  5 5 5 5 4 3 3 3 20 16 ...</code></pre>
</div>
</div>
<p><br></p>
<p>This data set is from the paper by Curtis and Wang (1998). They looked at the effect of increased CO<span class="math inline">\(_2\)</span> on plant traits (mainly changes in biomass). There is experimental details (sometimes called moderators) including species and functional group. There is also means (m), standard deviations (sd) and sample sizes (n) for the control group (1) and experimental group (2) in the last few columns.</p>
<p><img src="./img/forest.jpg" class="img-fluid" alt="A photo of tree trunks, bushes and ferns."> <button type="button" class="btn btn-success"><p></p>
<p>To get a final, clean dataset like this takes a lot of work going through many papers. One of the final challenges will give you an idea of how difficult it can be to get to this stage. </p></button></p>
<p><br></p>
</section>
<section id="calculating-standardized-effect-sizes" class="level2">
<h2 class="anchored" data-anchor-id="calculating-standardized-effect-sizes">Calculating ‘standardized’ effect sizes</h2>
<p>To compare the effect of increased CO<span class="math inline">\(_2\)</span> across multiple studies, we first need to calculate an <strong>effect size</strong> for each study - a metric that quantifies the difference between our control and experimental groups.</p>
<button type="button" class="btn btn-success">
Effect size reminder. If experiment 1 measures the weights of swans and geese and experiment 2 measures the weight of swans and robins, the effect size is bigger in experiment 2. There is a bigger effect of species on weight in experiment 2.
</button>
<p><br></p>
<p>There are several ‘standardized’ effect sizes. When we have two groups to compare, we have a choice of two effect size statistics we could use.</p>
<ol type="1">
<li>The first choice is called ‘response ratio’, which is usually presented in its natural logarithm form (lnRR).</li>
</ol>
<details>
<summary>
<strong>Formula for lnRR</strong>
</summary>
<p><span class="math display">\[\begin{equation}
\mathrm{lnRR}=\ln\left({\frac{\bar{x}_{E}}{\bar{x}_{C}}}\right)
\end{equation}\]</span></p>
</details>
<p><br></p>
<p>The sampling error variance for lnRR is also needed.</p>
<details>
<summary>
<strong>Formula for calculating sample error variance for lnRR</strong>
</summary>
<p><span class="math display">\[\begin{equation}
se^2_\mathrm{lnRR}=\frac{sd^2_{C}}{n_{C}\bar{x}^2_{C}}+\frac{sd^2_{E}}{n_{E}\bar{x}^2_{E}}
\end{equation}\]</span></p>
</details>
<ol start="2" type="1">
<li>The second option of standardised effect size is standardized mean difference (SMD also known as Cohen’s <span class="math inline">\(d\)</span> or Hedge’s <span class="math inline">\(d\)</span> or <span class="math inline">\(g\)</span>; there are some subtle differences between d and g, but we do not worry about them for now.)</li>
</ol>
<details>
<summary>
<strong>Formula for calculating SMD</strong>
</summary>
<p>In the formula below:<br>
* <span class="math inline">\(\bar{x}_{C}\)</span> and <span class="math inline">\(\bar{x}_{E}\)</span> are the means of the control and experimental group, respectively<br>
* <span class="math inline">\(sd\)</span> is sample standard deviation<br>
* <span class="math inline">\(n\)</span> is sample size</p>
<p><span class="math display">\[\begin{equation}
\mathrm{SMD}=\frac{\bar{x}_{E}-\bar{x}_{C}}{\sqrt{\frac{(n_{C}-1)sd^2_{C}+(n_{E}-1)sd^2_{E}}{n_{C}+n_{E}-2}}}
\end{equation}\]</span></p>
</details>
<p><br></p>
<p>We also need to calculate the SMD’s sample error variance for each study.</p>
<details>
<summary>
<strong>Formula for calculating sample error variance</strong>
</summary>
<p><span class="math display">\[\begin{equation}
se^2_{\mathrm{SMD}}= \frac{n_{C}+n_{E}}{n_{C}n_{E}}+\frac{\mathrm{SMD}^2}{2(n_{C}+n_{E})}
\end{equation}\]</span></p>
</details>
<p><br></p>
<p>The square root of this is referred to as ‘standard error’. The inverse of this (the inverse of a number is when you divide 1 by it e.g.<span class="math inline">\(1/se^2\)</span>) is used as ‘weight’ (studies with bigger sample sizes will have bigger ‘weight’ in the analysis)</p>
<p><br></p>
<p><br></p>
<p>We can get R to calculate standardised effect sizes for each study (ie every row) using the function <code>escalc()</code> in <code>metafor</code>.</p>
<p>To obtain the response ratio (lnRR), we use:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lnRR <span class="ot">&lt;-</span> <span class="fu">escalc</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="st">"ROM"</span>, <span class="at">n1i =</span> dat<span class="sc">$</span>n1i, <span class="at">n2i =</span> dat<span class="sc">$</span>n2i,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1i =</span> dat<span class="sc">$</span>m1i, <span class="at">m2i =</span> dat<span class="sc">$</span>m2i,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd1i =</span> dat<span class="sc">$</span>sd1i, <span class="at">sd2i =</span> dat<span class="sc">$</span>sd2i</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<details>
<summary>
<strong>Code Explained</strong>
</summary>
<p>Note: in the example dataset <code>dat</code> the columns for the sample sizes, means and standard deviation have been given the same name as the arguments that are used in <code>escalc()</code></p>
<ul>
<li><code>n1i</code> and <code>n2i</code> are the sample sizes</li>
<li><code>m1i</code> and <code>m2i</code> are the means</li>
<li><code>sd1i</code> and <code>sd2i</code> the standard deviations from each study</li>
</ul>
</details>
<p>The <code>lnRR</code> object created has an effect size (yi) and its variance (vi) for each study.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
       yi     vi 
1  0.5470 0.0385 
2  0.1425 0.0175 
3  0.4378 0.0328 
4 -0.1134 0.0295 
5  0.1172 0.0468 
6  0.5183 0.0355 </code></pre>
</div>
</div>
<p><br></p>
<p><br></p>
<p>We won’t do this now, but to obtain the alternative standardised mean difference (SMD), we would change the <code>measure =</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SMD</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>SMD <span class="ot">&lt;-</span> <span class="fu">escalc</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="st">"SMD"</span>, <span class="at">n1i =</span> dat<span class="sc">$</span>n1i, <span class="at">n2i =</span> dat<span class="sc">$</span>n2i,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1i =</span> dat<span class="sc">$</span>m1i, <span class="at">m2i =</span> dat<span class="sc">$</span>m2i,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd1i =</span> dat<span class="sc">$</span>sd1i, <span class="at">sd2i =</span> dat<span class="sc">$</span>sd2i</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<button type="button" class="btn btn-success">
<p>We can calculate many different kinds of effect sizes with <kbd><code>escalc</code></kbd>; other common effect size statistics include <span class="math inline">\(Zr\)</span> (Fisher’s z-transformed correlation) which you would use if the meta-analysis was analysing studies that reported correlations oppose to comparing two groups.</p>
</button>
<p><br></p>
<p>The original paper used lnRR so we will use it, but you will repeat the analysis in the <strong>Challenge</strong> below using SMD to see if it changes the results.</p>
<p><br></p>
<p>Add the lnRR effect sizes to the original data set with <code>bind_cols()</code> from the package <code>dplyr</code> (some people use <code>cbind()</code> for this).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(dat, lnRR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>You should see yi (effect size) and vi (sampling variance) are added.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   102 obs. of  22 variables:
 $ id      : int  21 22 27 32 35 38 44 63 86 87 ...
 $ paper   : int  44 44 121 121 121 121 159 183 209 209 ...
 $ genus   : chr  "ALNUS" "ALNUS" "ACER" "QUERCUS" ...
 $ species : chr  "RUBRA" "RUBRA" "RUBRUM" "PRINUS" ...
 $ fungrp  : chr  "N2FIX" "N2FIX" "ANGIO" "ANGIO" ...
 $ co2.ambi: num  350 350 350 350 350 350 350 395 350 350 ...
 $ co2.elev: num  650 650 700 700 700 700 700 795 700 700 ...
 $ units   : chr  "ul/l" "ul/l" "ppm" "ppm" ...
 $ time    : int  47 47 59 70 64 50 730 365 365 365 ...
 $ pot     : chr  "0.5" "0.5" "2.6" "2.6" ...
 $ method  : chr  "GC" "GC" "GH" "GH" ...
 $ stock   : chr  "SEED" "SEED" "SEED" "SEED" ...
 $ xtrt    : chr  "FERT" "FERT" "NONE" "NONE" ...
 $ level   : chr  "HIGH" "CONTROL" "." "." ...
 $ m1i     : num  6.82 2.6 2.99 5.91 4.61 ...
 $ sd1i    : num  1.77 0.667 0.856 1.742 1.407 ...
 $ n1i     : int  3 5 5 5 4 5 3 3 20 16 ...
 $ m2i     : num  3.94 2.25 1.93 6.62 4.1 ...
 $ sd2i    : num  1.116 0.328 0.552 1.631 1.257 ...
 $ n2i     : int  5 5 5 5 4 3 3 3 20 16 ...
 $ yi      : num  0.547 0.143 0.438 -0.113 0.117 ...
  ..- attr(*, "ni")= int [1:102] 8 10 10 10 8 8 6 6 40 32 ...
  ..- attr(*, "measure")= chr "ROM"
 $ vi      : num  0.0385 0.0175 0.0328 0.0295 0.0468 ...</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="forest-plots" class="level2">
<h2 class="anchored" data-anchor-id="forest-plots">Forest Plots</h2>
<p>Forest plots are a common way of visualising the effect sizes and their 95% confidence intervals, also known as CIs, (based on sampling error variance) for each of the studies in the meta-analysis. The <code>forest()</code> function can create this plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(dat<span class="sc">$</span>yi, dat<span class="sc">$</span>vi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="metaanalyses_files/figure-html/forest-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Unless you have a large screen, you may not be able to see the detail in this forest plot. Let’s plot just the first 12 studies just so we can inspect them ourselves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(dat<span class="sc">$</span>yi[<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>], dat<span class="sc">$</span>vi[<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="metaanalyses_files/figure-html/forest2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p><strong>Challenge</strong></p>
<p>Do an internet search to find out how to interpret forest plots. Answer the questions below.</p>
<ul>
<li>What do the squares mean?</li>
<li>Why is there a dotted line at 0?</li>
<li>Some forest plots you see on the internet might have a diamond. What does the diamond represent?</li>
<li>Find forest plots where the studies are in order? Does this help you view the figure?</li>
<li>Can you find any forest plots where colour denotes if they cross 0 or not.</li>
</ul>
<p><br></p>
<p><strong>Challenge</strong></p>
<p>Now add the SMD values (the alternative ones to lnRR) to <code>dat</code> and create a forest plot with them. Compare the two forest plots.</p>
<button type="button" class="btn btn-success">
Don’t get confused if you end up with two lots of <code>yi</code> and <code>vi</code> values since you have already created these when you did the lnRR method.
</button>
<details>
<summary>
<strong>Solution</strong>
</summary>
<p>Use the SMD object created above. Add the vi and yi columns in SMD to the dataset dat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(dat, SMD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you view dat or run <code>str(dat)</code> you will see R has renamed the <code>vi</code> and <code>yi</code> columns. This means you have the lnRR values and then the SMD values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   102 obs. of  24 variables:
 $ id      : int  21 22 27 32 35 38 44 63 86 87 ...
 $ paper   : int  44 44 121 121 121 121 159 183 209 209 ...
 $ genus   : chr  "ALNUS" "ALNUS" "ACER" "QUERCUS" ...
 $ species : chr  "RUBRA" "RUBRA" "RUBRUM" "PRINUS" ...
 $ fungrp  : chr  "N2FIX" "N2FIX" "ANGIO" "ANGIO" ...
 $ co2.ambi: num  350 350 350 350 350 350 350 395 350 350 ...
 $ co2.elev: num  650 650 700 700 700 700 700 795 700 700 ...
 $ units   : chr  "ul/l" "ul/l" "ppm" "ppm" ...
 $ time    : int  47 47 59 70 64 50 730 365 365 365 ...
 $ pot     : chr  "0.5" "0.5" "2.6" "2.6" ...
 $ method  : chr  "GC" "GC" "GH" "GH" ...
 $ stock   : chr  "SEED" "SEED" "SEED" "SEED" ...
 $ xtrt    : chr  "FERT" "FERT" "NONE" "NONE" ...
 $ level   : chr  "HIGH" "CONTROL" "." "." ...
 $ m1i     : num  6.82 2.6 2.99 5.91 4.61 ...
 $ sd1i    : num  1.77 0.667 0.856 1.742 1.407 ...
 $ n1i     : int  3 5 5 5 4 5 3 3 20 16 ...
 $ m2i     : num  3.94 2.25 1.93 6.62 4.1 ...
 $ sd2i    : num  1.116 0.328 0.552 1.631 1.257 ...
 $ n2i     : int  5 5 5 5 4 3 3 3 20 16 ...
 $ yi...21 : num  0.547 0.143 0.438 -0.113 0.117 ...
  ..- attr(*, "ni")= int [1:102] 8 10 10 10 8 8 6 6 40 32 ...
  ..- attr(*, "measure")= chr "ROM"
 $ vi...22 : num  0.0385 0.0175 0.0328 0.0295 0.0468 ...
 $ yi...23 : num  1.822 0.592 1.329 -0.38 0.332 ...
  ..- attr(*, "ni")= int [1:102] 8 10 10 10 8 8 6 6 40 32 ...
  ..- attr(*, "measure")= chr "SMD"
 $ vi...24 : num  0.741 0.418 0.488 0.407 0.507 ...</code></pre>
</div>
</div>
<p>Now create a forest plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(dat<span class="sc">$</span>yi...<span class="dv">23</span>, dat<span class="sc">$</span>vi...<span class="dv">24</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="metaanalyses_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If you want to view the previous forest plot for comparison try the blue arrow under the <code>Plots</code> tab. Alternative you could assign the plots and use that name to call them and view them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plotlnRR <span class="ot">&lt;-</span> <span class="fu">forest</span>(dat<span class="sc">$</span>yi...<span class="dv">21</span>, dat<span class="sc">$</span>vi...<span class="dv">22</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>plotlnRR</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>plotSMD <span class="ot">&lt;-</span> <span class="fu">forest</span>(dat<span class="sc">$</span>yi...<span class="dv">23</span>, dat<span class="sc">$</span>vi...<span class="dv">24</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>plotSMD</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Comparing the forest plots, there does seem to be differences. Keep in mind that you may want to investigate how using lnRR or SMD may or may not affect the analysis further on.</p>
</details>
<p><br></p>
<p><br></p>
</section>
</section>
<section id="calculating-the-overall-effect-size" class="level1">
<h1>Calculating the overall effect size</h1>
<p>After calculating effect sizes, we can run statistical models to estimate the overall mean effect size.</p>
<p>There are two main models for meta-analysis: 1) the <strong>‘common-effect’</strong> model and 2) the <strong>random-effect</strong> model (actually there’s 3 types, but the third one is the extension of the second model).</p>
<button type="button" class="btn btn-success">
<p>Section Q4 and Fig. 4 in <a href="https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-017-0357-7">Nakagawa et al.&nbsp;2017</a> gives a longer explanation and visual representation of the different models.</p>
</button>
<p><br></p>
<section id="common-effect-model" class="level2">
<h2 class="anchored" data-anchor-id="common-effect-model">Common-effect model</h2>
<p>This model estimates the overall mean while considering weights. Weights are used so that different studies with smaller or larger sample sizes have less or more influence in the calculation of the overall effect size.</p>
<details>
<summary>
<strong>Common-effect model formula and explanation</strong>
</summary>
<p><span class="math display">\[\begin{equation}
y_i=b_0+e_i,
\\
e_i\sim \mathcal{N}(0,v_i),
\end{equation}\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> is the <span class="math inline">\(i\)</span>th effect size (from <span class="math inline">\(i\)</span>th study), <span class="math inline">\(b_0\)</span> is the overall mean (or meta-analytic mean), <span class="math inline">\(e_i\)</span> is a deviation from the overall mean. <span class="math inline">\(e_i\)</span> is equivalent to a normal distribution with a mean of 0 and variance of <span class="math inline">\(v_i\)</span>. <span class="math inline">\(v_i\)</span> is the study specific sampling variance. Note that weights for this model are <span class="math inline">\(1/v_i\)</span>.</p>
</details>
<p><br></p>
<p>This model assumes that all the studies sampled from the same population and therefore there is a common mean for all studies. For example, all studies used the same species. This is rare in meta-analysis as the Curtis and Wang 1998 data shows where studies span many different species.</p>
<p><br></p>
</section>
<section id="random-effects-model" class="level2">
<h2 class="anchored" data-anchor-id="random-effects-model">Random-effects model</h2>
<p>A random-effect model does not make this assumption and therefore can be used when studies have been sampled from different populations.</p>
<details>
<summary>
<strong>Random-effect model formula and explanation</strong>
</summary>
<p><span class="math display">\[\begin{equation}
y_i = b_0 + s_i + e_i, \\
s_i \sim \mathcal{N}(0, \tau^2), \\
e_i \sim \mathcal{N}(0, v_i)
\end{equation}\]</span></p>
<p>where <span class="math inline">\(s_i\)</span> is a study-specific deviation from the overall mean for <span class="math inline">\(i\)</span>th study. As the second formula indicates, <span class="math inline">\(s_i\)</span> is normally distributed with the between-study variance which is <span class="math inline">\(\tau^2\)</span>. Note that weights for this model are <span class="math inline">\(1/(\tau^2+v_i)\)</span>. We revisit this point.</p>
</details>
<p><br></p>
<p>Unlike the common-effect model, a random-effect model assumes that different studies have different population means.</p>
<p><br></p>
</section>
<section id="running-a-common-effect-model" class="level2">
<h2 class="anchored" data-anchor-id="running-a-common-effect-model">Running a common-effect model</h2>
<p>Let’s use the function <code>rma</code> from <code>metafor</code> to run a common-effect model using the effect sizes <code>yi</code> and variances <code>vi</code> we calculated earlier. (Note: make sure those columns are still called <code>yi</code> and <code>vi</code>.)</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>common_m <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">method =</span> <span class="st">"FE"</span>, <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We specify the effect size (yi), its variance (vi), the method (“FE” for fixed-effect which is another name for common-effect) and the data frame (dat).</p>
<p><br></p>
<p>To see the output, use <code>summary</code> on the model object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(common_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Fixed-Effects Model (k = 102)

   logLik   deviance        AIC        BIC       AICc   
-245.9580   769.0185   493.9160   496.5410   493.9560   

I^2 (total heterogeneity / total variability):   86.87%
H^2 (total variability / sampling variability):  7.61

Test for Heterogeneity:
Q(df = 101) = 769.0185, p-val &lt; .0001

Model Results:

estimate      se     zval    pval   ci.lb   ci.ub      
  0.2088  0.0054  38.3374  &lt;.0001  0.1982  0.2195  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The overall mean is statistically significant (under <code>Model Results</code> look at <code>pval</code>). This indicates it is significantly different from 0 and therefore there <strong>is</strong> an effect of the CO<span class="math inline">\(_2\)</span> treatments on plant biomass.</p>
<p>The overall mean is under <code>estimate</code> and it’s around 0.2. What does 0.2 mean? The effect sizes were response ratios on a logarithmic scale (lnRR). We can use <code>exp()</code> to convert this back into a response ratio of the control and experimental means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.221403</code></pre>
</div>
</div>
<p>We can say that the plant trait (i.e.&nbsp;biomass) was 22% larger in the experimental group (RR<span class="math inline">\(=\bar{x}_{E}/\bar{x}_{C}\)</span>), which is a pretty large effect (remember to interpret results in a biological meaningful way).</p>
<p><br></p>
</section>
<section id="running-a-random-effects-model" class="level2">
<h2 class="anchored" data-anchor-id="running-a-random-effects-model">Running a random-effects model</h2>
<p>Now, we move onto the random-effects model - a more realistic model because these studies were on different species. Again, we use the <code>rma</code> function, but this time change the method to REML which is the default and the best method for the random-effect meta-analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>random_m <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">data =</span> dat)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(random_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 102; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
  7.0449  -14.0898  -10.0898   -4.8596   -9.9674   

tau^2 (estimated amount of total heterogeneity): 0.0262 (SE = 0.0053)
tau (square root of estimated tau^2 value):      0.1619
I^2 (total heterogeneity / total variability):   88.90%
H^2 (total variability / sampling variability):  9.01

Test for Heterogeneity:
Q(df = 101) = 769.0185, p-val &lt; .0001

Model Results:

estimate      se     zval    pval   ci.lb   ci.ub      
  0.2553  0.0198  12.8899  &lt;.0001  0.2165  0.2941  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Compare the overall mean from this model with the common-effect model. Oh, the overall mean of the random-effects model (0.255) is actually bigger than that of the common-effect model! OK, that sometimes happens (we will find out that this probably is an over-estimation later in the publication bias section).</p>
<p>We expect the 95% CI (under <code>ci.lb</code> and <code>ci.ub</code>) to be wider (i.e.&nbsp;more realistic) in this random-effects model as this model has a more realistic assumption than the common-effect model.</p>
<p><br></p>
</section>
<section id="understanding-heterogeneity" class="level2">
<h2 class="anchored" data-anchor-id="understanding-heterogeneity">Understanding heterogeneity</h2>
<p>There are other numbers in the output. We have <code>tau^2</code> (<span class="math inline">\(\tau^2\)</span>) and <code>I^2</code> (<span class="math inline">\(I^2\)</span>), two very common measures of heterogeneity (note that <code>H^2</code>, or <span class="math inline">\(H^2\)</span> is a transformation of <span class="math inline">\(I^2\)</span>).</p>
<button type="button" class="btn btn-success">
<p>Heterogeneity is variation in effect sizes, which is not accounted for by the sampling error variance/random chance. In other words, how consistent the results are across all the studies. This is real variation in the data.</p>
</button>
<p><br></p>
<p><span class="math inline">\(I^2\)</span> is an important index as it can tell the percentage of real variation in your meta-analytic data.</p>
<details>
<summary>
<strong>Formula for <span class="math inline">\(I^2\)</span></strong>
</summary>
<p><span class="math display">\[\begin{equation}
I^2=\frac{\tau^2}{(\tau^2+\bar{v})},
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\bar{v}\)</span> is a representative value of <span class="math inline">\(v_i\)</span> (or think <span class="math inline">\(\bar{v}\)</span> as the average of <span class="math inline">\(v_i\)</span> although it is not quite it). Note that the denominator is the whole variance which exists in the data.</p>
</details>
<p><br></p>
<p>The benchmark values for <span class="math inline">\(I^2\)</span> are 25, 50 and 75% for low, moderate and high heterogeneity, respectively (<a href="https://pubmed.ncbi.nlm.nih.gov/12958120/">Higgins et al., 2003</a>.)</p>
<p>Our <span class="math inline">\(I^2\)</span> value is 88.9% so very high. The output also shows a <code>Test for Heterogeneity</code> or a <span class="math inline">\(Q\)</span> test. As you might expect, <span class="math inline">\(I^2\)</span> is statistically significant meaning there is heterogeniety.</p>
<p><br></p>
<p><a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.1591">Senior et al.&nbsp;2016</a> did a meta-analysis of meta-analyses looking at the average value of <span class="math inline">\(I^2\)</span> in the field of ecology and evolution. The average value was 92%! This indicates that we usually need to fit the random-effects model rather than the common-effect model because the latter assumes heterogeneity to be zero or <span class="math inline">\(\tau^2=0\)</span> and <span class="math inline">\(I^2 = 0\)</span>.</p>
<p><br></p>
</section>
</section>
<section id="meta-regression-the-random-effects-model" class="level1">
<h1>Meta-regression (the random-effects model)</h1>
<p>The significant overall effect size and the existence of heterogeneity sets a scene for meta-regression. This is where we now put predictors (‘moderators’ in the meta-analytic terminology) into our model to explain the heterogeneity. This is the equivalent to normal regression models.</p>
<p>In this example, let’s fit three moderators that were collected by the authors: 1) <code>time</code> (how long the experiment was), 2) <code>method</code> (different ways of increasing CO<span class="math inline">\(_2\)</span>), and 3) <code>fungroup</code> (functional group, i.e., angiosperm, gymnosperm or N<span class="math inline">\(_2\)</span> fixer).</p>
<p>We use <code>rma()</code> again, but add a model statement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>metareg <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">mod =</span> <span class="sc">~</span> time <span class="sc">+</span> method <span class="sc">+</span> fungrp, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">data =</span> dat)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(metareg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 102; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
  5.1938  -10.3876    3.6124   21.5628    4.8851   

tau^2 (estimated amount of residual heterogeneity):     0.0267 (SE = 0.0056)
tau (square root of estimated tau^2 value):             0.1634
I^2 (residual heterogeneity / unaccounted variability): 87.16%
H^2 (unaccounted variability / sampling variability):   7.79
R^2 (amount of heterogeneity accounted for):            0.00%

Test for Residual Heterogeneity:
QE(df = 96) = 658.4083, p-val &lt; .0001

Test of Moderators (coefficients 2:6):
QM(df = 5) = 2.9089, p-val = 0.7140

Model Results:

             estimate      se     zval    pval    ci.lb   ci.ub      
intrcpt        0.3043  0.0516   5.8934  &lt;.0001   0.2031  0.4055  *** 
time          -0.0001  0.0001  -1.0509  0.2933  -0.0002  0.0001      
methodGH      -0.0369  0.0567  -0.6501  0.5157  -0.1481  0.0743      
methodOTC      0.0308  0.0902   0.3410  0.7331  -0.1461  0.2076      
fungrpGYMNO   -0.0454  0.0605  -0.7501  0.4532  -0.1640  0.0732      
fungrpN2FIX    0.0044  0.1701   0.0258  0.9794  -0.3291  0.3379      

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Look at the R<span class="math inline">\(^2\)</span> value - the moderators do not explain anything! Also, the <code>Test of Moderators</code> (again the Q value) say they are not significant. A terrible model!</p>
<p><strong>Challenge</strong></p>
<p>Using your knowledge of how you have previously assessed data and models, do some more analyses to find out if these non significant results are likely true.</p>
<div class="cell">

</div>
<p><br></p>
</section>
<section id="checking-for-publication-bias" class="level1">
<h1>Checking for publication bias</h1>
<p>It seems like an CO<span class="math inline">\(_2\)</span> increase promotes plant growth, but this is assuming the data set we have does not suffer from <strong>publication bias</strong>.</p>
<button type="button" class="btn btn-success">
<p>Publication bias in its simplest form is that significant results are more likely to be published than non-significant results</p>
</button>
<p><br></p>
<p>There are several methods people use to assess if there is publication bias. The two commonest methods, often used together, are: 1) funnel plot, which is used to detect funnel asymmetry (a sign of publication bias), and 2) Egger’s regression test with which you test funnel asymmetry statistically.</p>
<p><br></p>
<section id="funnel-plot" class="level2">
<h2 class="anchored" data-anchor-id="funnel-plot">Funnel plot</h2>
<p>To create a funnel plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(random_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="metaanalyses_files/figure-html/funnel-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The x axis is effect size. The overall effect size is plotted as a dotted vertical line. Each point shows a study’s effect size and standard error on the y axis. Note the y axis has 0 at the top.</p>
<p><strong>Challenge</strong></p>
<p>What sample sizes are the studies with high standard error likely to have? What does this funnel plot show in terms of whether it is symmetrical or not? What does that mean?</p>
<div class="cell">

</div>
<p><br></p>
</section>
<section id="eggers-test" class="level2">
<h2 class="anchored" data-anchor-id="eggers-test">Egger’s test</h2>
<p>To run Egger’s test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regtest</span>(random_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Test for Funnel Plot Asymmetry

Model:     mixed-effects meta-regression model
Predictor: standard error

Test for Funnel Plot Asymmetry: z = 3.2046, p = 0.0014
Limit Estimate (as sei -&gt; 0):   b = 0.1584 (CI: 0.0890, 0.2278)</code></pre>
</div>
</div>
<p>The Egger’s test p value is significant suggesting asymetry. But we need to be careful. Funnel asymmetry can be caused not only by publication bias, but also by heterogeneity (one or more undetected moderators are distorting a funnel shape). Given we have a lot of unexplained variance (i.e.&nbsp;heterogeneity), we cannot be sure what is causing this asymmetry.</p>
<p><br></p>
</section>
<section id="trim-and-fill" class="level2">
<h2 class="anchored" data-anchor-id="trim-and-fill">Trim-and-fill</h2>
<p>We can use the alternative trim-and-fill method through the function <code>trimfill()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>tf_m <span class="ot">&lt;-</span> <span class="fu">trimfill</span>(random_m)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>tf_m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimated number of missing studies on the left side: 13 (SE = 6.5629)

Random-Effects Model (k = 115; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0421 (SE = 0.0076)
tau (square root of estimated tau^2 value):      0.2053
I^2 (total heterogeneity / total variability):   92.06%
H^2 (total variability / sampling variability):  12.59

Test for Heterogeneity:
Q(df = 114) = 872.7669, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2166  0.0227  9.5234  &lt;.0001  0.1721  0.2612  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We get a funnel plot by passing the result through <code>funnel()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(tf_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="metaanalyses_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see this method uses the asymmetry to add more points and provide a revised overall mean, which is smaller than that of the original random-effect model. Although this effect is still significant, this method could turn a significant overall mean into a non-significant one. But rather than taking this as a real estimate of the overall mean, we need to see this as a part of our sensitivity analysis.</p>
<p><br></p>
<button type="button" class="btn btn-success">
<p>Sensitivity analyses involve various statistical methods that test how the overall effect size changes depending on the decisions made during the meta-analysis. These decisions will have affected what studies and data was included in the calculation.</p>
</button>
<p><br></p>
<p>There are more methods for publication bias tests, none of which are perfect, but it is important to do some of these tests (for more see <a href="https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-017-0357-7">Nakagawa et al., 2017</a> and references therein).</p>
<p><br></p>
</section>
</section>
<section id="challenges" class="level1">
<h1>Challenges</h1>
<p>Use the <a href="https://doi.org/10.1016/j.jhazmat.2021.127211">meta analysis by Li et al., (2002)</a> which looks at stress in bivalves caused by microplastics using various measures.</p>
<p>Li et al., (2022). Is microplastic an oxidative stressor? Evidence from a meta-analysis on bivalves. Journal of Hazardous Materials, 423, 127211. DOI: https://doi.org/10.1016/j.jhazmat.2021.127211</p>
<p><strong>Challenge 1</strong></p>
<p>To understand how means and standard deviations are collated, look at <a href="https://doi.org/10.1016/j.ecoenv.2020.110871">the study below</a> which is just one of the 25 studies used in Li et al.’s meta analysis. Try to find the values that were used for the measurement SOD (superoxide dismutase).</p>
<p>Webb, S., Gaw, S., Marsden, I. D., &amp; McRae, N. K. (2020). Biomarker responses in New Zealand green-lipped mussels Perna canaliculus exposed to microplastics and triclosan. Ecotoxicology and Environmental Safety, 201, 110871. DOI: https://doi.org/10.1016/j.ecoenv.2020.110871</p>
<details>
<summary>
<strong>Answer</strong>
</summary>
<p>You may have looked in the “Oxidative stress” part of the Results section or Fig 4B but found that the means and standard deviation are not given. There is a link under “Appendix A.Supplementary data”. Following this link gives the message “Data will be made available on request”. While it is preferable to contact authors to obtain accurate data, people sometimes resort to using image analysis software to calculate means and standard deviations from high resolution graphs. The authors of the meta-analysis explain:</p>
<blockquote class="blockquote">
<p>“When the raw data of the experiments could not be found in the article, numerical values were extracted from the graphs by a digital ruler (Plot Digitizer 2.6.8).”</p>
</blockquote>
</details>
<p><br></p>
<p><strong>Challenge 2</strong></p>
<p>On the <a href="https://doi.org/10.1016/j.jhazmat.2021.127211">webpage for Li et al.’s meta analysis</a>, find the Appendix A Supplementary material section and download the raw data used in the meta analysis.</p>
<p>Read the sheet for SOD into R.</p>
<details>
<summary>
<strong>Tips</strong>
</summary>
<p>Be aware there are multiple workbooks in the excel file, use only the SOD one. You will need to save a copy of the file.<br>
Decide what format to save the file as, for example, csv or excel.<br>
Remember the file format determines what function you use in R.<br>
Once read in, check the data looks as you would expect by viewing it or using <code>head()</code>.<br>
Consider changing the names of the variables.</p>
</details>
<p><br></p>
<p><strong>Challenge 3</strong></p>
<p>Using the methods and code for the CO<sub>2</sub> and plant example above, carry out a meta-analysis on the bivalve SOD data. If you get as far as doing a meta-regression you could use particle size, species or exposure time as moderators.</p>
<details>
<summary>
<strong>Tips</strong>
</summary>
<p>Adapt the code remembering to change the names of the variables and dataset.<br>
You may have to wrangle your data if a variable is not in the format a function expects it to be in. For example, remove units such as days or change text into categorical data.</p>
</details>
<button type="button" class="btn btn-success">
If you seem to be spending lots of time cleaning the data don’t worry - that’s normal! Most data scientists would say two-thirds of their time would typically be spend cleaning the data and one third analysing it.
</button>
<p><br></p>
</section>
<section id="further-help-and-references" class="level1">
<h1>Further help and references</h1>
<p>Worked examples on the <a href="http://www.metafor-project.org/doku.php">metafor package’s website</a>.</p>
<p style="margin-left:.5in;text-indent:-.5in">
Curtis, P. S., and X. Z. Wang. 1998. A meta-analysis of elevated CO2 effects on woody plant mass, form, and physiology. <em>Oecologia</em> 113:299-313.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Henmi, M., and J. B. Copas. 2010. Confidence intervals for random effects meta-analysis and robustness to publication bias. <em>Statistics in Medicine</em> 29:2969-2983.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Higgins, J. P. T., S. G. Thompson, J. J. Deeks, and D. G. Altman. 2003. Measuring inconsistency in meta-analyses. <em>British Medical Journal</em> 327:557-560.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Nakagawa, S., R. Poulin, K. Mengersen, K. Reinhold, L. Engqvist, M. Lagisz, and A. M. Senior. 2015. Meta-analysis of variation: ecological and evolutionary applications and beyond. <em>Methods in Ecology and Evolution</em> 6:143-152.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Nakagawa, S., D. W. A. Noble, A. M. Senior, and M. Lagisz. 2017. Meta-evaluation of meta-analysis: ten appraisal questions for biologists. <em>BMC Biology</em> 15:18.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Senior, A. M., C. E. Grueber, T. Kamiya, M. Lagisz, K. O’Dwyer, E. S. A. Santos, and S. Nakagawa. 2016. Heterogeneity in ecological and evolutionary meta-analyses: its magnitude and implications. <em>Ecology</em> 97:3293-3299.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Viechtbauer, W. 2010. Conducting meta-analyses in R with the metafor package. <em>Journal of Statistical Software</em> 36:1-48.
</p>
<p><br></p>
<p><br></p>
<p>Adapted from <a href="https://github.com/nicercode/EnvironmentalComputing">EnvironmentalComputing</a>. Authors: Shinichi Nakagawa and Malgorzata (Losia) Lagisz</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><a href="https://creativecommons.org/">CC Licensed</a></div>   
    <div class="nav-footer-right"><a href="https://github.com/acriach/BLGY5121MAdvStats">Source</a></div>
  </div>
</footer>



</body></html>